// Mocks generated by Mockito 5.0.10 from annotations
// in bloodglucose_monitoring_flutterapp/test/unit/unit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloodglucose_monitoring_flutterapp/controller/helper/glucose_service_helper.dart'
    as _i2;
import 'package:bloodglucose_monitoring_flutterapp/model/glucose.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [GlucoseServiceHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockGlucoseServiceHelper extends _i1.Mock
    implements _i2.GlucoseServiceHelper {
  MockGlucoseServiceHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Glucose>> fetchGlucoseList() =>
      (super.noSuchMethod(Invocation.method(#fetchGlucoseList, []),
              returnValue: Future<List<_i4.Glucose>>.value(<_i4.Glucose>[]))
          as _i3.Future<List<_i4.Glucose>>);
  @override
  _i3.Future<void> postGlucoseJson(List<_i4.Glucose>? glucoseList) =>
      (super.noSuchMethod(Invocation.method(#postGlucoseJson, [glucoseList]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
}
